name: "Unpublish old versions"

on:
  workflow_dispatch:
    inputs:
      delete_packages:
        type: boolean
        description: Delete packages? otherwise dry-run mode will be used
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean-npm-versions:
    name: Unpublish versions next, preview, main...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: FuelLabs/github-actions/setups/node@master
        with:
          pnpm-version: 9.13.1

      - uses: FuelLabs/github-actions/setups/npm@master

      - run: |
          node ./scripts/unpublish.js
        env:
          DELETE_PACKAGES: ${{ github.event.inputs.delete_packages }}
